name: book_store
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  get_it: ^7.2.0
  injectable: ^2.3.2
  uuid: ^3.0.7
  flutter: 
    sdk: flutter
  cached_network_image: ^3.3.1
  flutter_launcher_icons: ^0.13.1
  freezed_annotation: ^2.1.0

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.4.5
  flutter_lints: ^3.0.2
  injectable_generator: ^2.4.1
  flutter_test: 
    sdk: flutter

flutter: 
  assets:
    - assets/images/
  uses-material-design: true

