name: book_store
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  get_it: ^7.2.0
  injectable: ^2.3.2
  flutter: 
    sdk: flutter
  cached_network_image: ^3.3.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^3.0.2
  injectable_generator: ^2.4.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

